name: STDL
channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - python=3.7.4
  - pytorch=1.3.0
  - torchvision=0.4.1
  - pillow=6.2.1 # version 7 breaks torchvision 0.4.2 and earlier
  - ipython>=7.9
  - numpy=1.18.1
  - scipy=1.4.1
  - scikit-learn=0.22.1
  - scikit-image=0.17.2
  - cudatoolkit
  - jupyterlab=1.2.6
  - matplotlib=3.2.1
  - jupyter=1.0.0
  - pandas=1.0.3
  - cython
  - pytest
  - tqdm=4.46.0
  - opencv=4.2.0
  - pip
  - pip:
    - nbmerge
    - pytest-xdist